spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: controle-horas
              uri: http://localhost:8082/
              predicates:
                - Path=/registros/**

